package com.localarcade.game;

import com.localarcade.player.Player;
import com.localarcade.player.PlayerRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;

@Service
public class SocialGameService {
    private static final List<String> CATEGORIES=List.of("ACES","DEUCES","THREES","FOURS","FIVES","SIXES","CHOICE","FOUR_KIND","FULL_HOUSE","SMALL_STRAIGHT","LARGE_STRAIGHT","YACHT");
    private final PlayerRepository repo; private final SecureRandom random=new SecureRandom();
    private final Deque<ChatMessage> chat=new ArrayDeque<>(); private final LinkedHashMap<String,Long> yachtLobby=new LinkedHashMap<>(); private final Set<String> yachtReady=new LinkedHashSet<>();
    private YachtGame yacht; private long messageSequence;
    SocialGameService(PlayerRepository repo){this.repo=repo;}

    public synchronized Map<String,Object> state(Player me){return Map.of("chat",new ArrayList<>(chat),"yacht",yachtView(),"categories",CATEGORIES);}
    public synchronized Map<String,Object> chat(Player p,String text){String clean=text==null?"":text.strip();if(clean.isBlank()||clean.length()>200)throw new IllegalArgumentException("채팅은 1~200자로 입력하세요.");chat.addLast(new ChatMessage(++messageSequence,p.getNickname(),clean,Instant.now().toString()));while(chat.size()>80)chat.removeFirst();return state(p);}

    @Transactional public synchronized Map<String,Object> joinYacht(Player p,long stake){if(yacht!=null&&!yacht.done)throw new IllegalArgumentException("이미 야추 게임이 진행 중입니다.");if(yachtLobby.containsKey(p.getId()))throw new IllegalArgumentException("이미 참가했습니다.");if(!yachtLobby.isEmpty()&&!Objects.equals(yachtLobby.values().iterator().next(),stake))throw new IllegalArgumentException("첫 참가자와 같은 참가 점수를 선택하세요.");if(!List.of(100L,500L,1000L).contains(stake))throw new IllegalArgumentException("선택할 수 없는 참가 점수입니다.");p.debit(stake);repo.save(p);yachtLobby.put(p.getId(),stake);yachtReady.remove(p.getId());return state(p);}
    public synchronized Map<String,Object> readyYacht(Player p){if(!yachtLobby.containsKey(p.getId()))throw new IllegalArgumentException("먼저 야추에 참여하세요.");if(!yachtReady.add(p.getId()))yachtReady.remove(p.getId());if(yachtLobby.size()>=2&&yachtReady.containsAll(yachtLobby.keySet()))startYacht(p);return state(p);}
    @Transactional public synchronized Map<String,Object> restartYacht(Player p,long stake){if(yacht!=null&&!yacht.done)throw new IllegalArgumentException("아직 게임이 진행 중입니다.");if(yacht!=null&&yacht.done)yacht=null;return joinYacht(p,stake);}
    public synchronized Map<String,Object> startYacht(Player p){if(yachtLobby.size()<2)throw new IllegalArgumentException("야추는 최소 2명이 필요합니다.");if(!yachtLobby.containsKey(p.getId()))throw new IllegalArgumentException("참가자만 시작할 수 있습니다.");yacht=new YachtGame(new ArrayList<>(yachtLobby.keySet()),yachtLobby.values().stream().mapToLong(Long::longValue).sum());yachtLobby.clear();yachtReady.clear();return state(p);}
    public synchronized Map<String,Object> roll(Player p,List<Boolean> held){YachtGame g=activeTurn(p);if(g.rolls>=3)throw new IllegalArgumentException("한 턴에는 3회까지 굴릴 수 있습니다.");for(int i=0;i<5;i++){boolean keep=g.rolls>0&&held!=null&&i<held.size()&&Boolean.TRUE.equals(held.get(i));g.held[i]=keep;if(!keep)g.dice[i]=random.nextInt(1,7);}g.rolls++;g.message=p.getNickname()+" 주사위 굴리기 "+g.rolls+"/3";return state(p);}
    @Transactional public synchronized Map<String,Object> score(Player p,String category,List<Integer> visibleDice){YachtGame g=activeTurn(p);if(g.rolls==0)throw new IllegalArgumentException("먼저 주사위를 굴리세요.");if(visibleDice==null||visibleDice.size()!=5||!visibleDice.equals(Arrays.stream(g.dice).boxed().toList()))throw new IllegalArgumentException("화면과 서버의 주사위가 달라 다시 동기화했습니다. 점수를 다시 선택하세요.");if(!CATEGORIES.contains(category))throw new IllegalArgumentException("점수 항목을 선택하세요.");Map<String,Integer> sheet=g.scores.get(p.getId());if(sheet.containsKey(category))throw new IllegalArgumentException("이미 기록한 항목입니다.");int points=calculate(category,g.dice);sheet.put(category,points);g.message=p.getNickname()+" · "+category+" +"+points;boolean finished=g.players.stream().allMatch(id->g.scores.get(id).size()==CATEGORIES.size());if(finished)finishYacht(g);else{g.turn=(g.turn+1)%g.players.size();Arrays.fill(g.dice,0);Arrays.fill(g.held,false);g.rolls=0;}return state(p);}
    @Transactional public synchronized Map<String,Object> cancelYacht(Player p){if(yacht==null||yacht.done||!yacht.players.contains(p.getId()))throw new IllegalArgumentException("진행 중인 야추 참가자만 종료할 수 있습니다.");long refund=yacht.pot/yacht.players.size();for(String id:yacht.players){Player player=repo.findById(id).orElse(null);if(player!=null){player.credit(refund);repo.save(player);}}yacht.done=true;yacht.message=p.getNickname()+"님이 게임을 종료했습니다. 참가 점수가 환불되었습니다.";return state(p);}
    @Transactional public synchronized Map<String,Object> leave(Player p){yachtReady.remove(p.getId());if(yachtLobby.remove(p.getId())!=null)return state(p);if(yacht!=null&&!yacht.done&&yacht.players.contains(p.getId())){List<String>remaining=yacht.players.stream().filter(id->!id.equals(p.getId())).toList();if(!remaining.isEmpty()){long each=yacht.pot/remaining.size();for(String id:remaining){Player winner=repo.findById(id).orElse(null);if(winner!=null){winner.credit(each);repo.save(winner);}}}yacht.done=true;yacht.message=p.getNickname()+" 기권 · 남은 참가자 승리";}return state(p);}
    public synchronized void removePlayer(String playerId){yachtLobby.remove(playerId);yachtReady.remove(playerId);if(yacht!=null&&!yacht.done&&yacht.players.contains(playerId)){yacht.done=true;yacht.message="플레이어 퇴장으로 게임이 종료되었습니다.";}}

    private YachtGame activeTurn(Player p){if(yacht==null||yacht.done)throw new IllegalArgumentException("진행 중인 야추 게임이 없습니다.");if(!yacht.players.get(yacht.turn).equals(p.getId()))throw new IllegalArgumentException("현재 내 턴이 아닙니다.");return yacht;}
    private int calculate(String c,int[]d){int sum=Arrays.stream(d).sum();int[]count=new int[7];for(int n:d)count[n]++;return switch(c){case"ACES"->count[1];case"DEUCES"->count[2]*2;case"THREES"->count[3]*3;case"FOURS"->count[4]*4;case"FIVES"->count[5]*5;case"SIXES"->count[6]*6;case"CHOICE"->sum;case"FOUR_KIND"->Arrays.stream(count).max().orElse(0)>=4?sum:0;case"FULL_HOUSE"->(Arrays.stream(count).anyMatch(x->x==3)&&Arrays.stream(count).anyMatch(x->x==2))||Arrays.stream(count).anyMatch(x->x==5)?sum:0;case"SMALL_STRAIGHT"->hasStraight(count,4)?15:0;case"LARGE_STRAIGHT"->hasStraight(count,5)?30:0;case"YACHT"->Arrays.stream(count).anyMatch(x->x==5)?50:0;default->0;};}
    private boolean hasStraight(int[]c,int length){int run=0;for(int i=1;i<=6;i++){run=c[i]>0?run+1:0;if(run>=length)return true;}return false;}
    private void finishYacht(YachtGame g){int best=g.players.stream().mapToInt(id->total(g.scores.get(id))).max().orElse(0);List<String>winners=g.players.stream().filter(id->total(g.scores.get(id))==best).toList();long share=g.pot/winners.size();for(String id:winners){Player p=repo.findById(id).orElseThrow();p.credit(share);repo.save(p);}g.done=true;g.message="우승: "+winners.stream().map(id->repo.findById(id).orElseThrow().getNickname()).reduce((a,b)->a+", "+b).orElse("");}
    private int total(Map<String,Integer>s){int base=s.values().stream().mapToInt(Integer::intValue).sum();return base+upperBonus(s);}
    private int upperBonus(Map<String,Integer>s){int upper=CATEGORIES.subList(0,6).stream().mapToInt(c->s.getOrDefault(c,0)).sum();return upper>=63?35:0;}
    private Object yachtView(){if(yacht==null)return Map.of("lobby",lobbyView());Map<String,Object>sheets=new LinkedHashMap<>(),bonuses=new LinkedHashMap<>();for(String id:yacht.players){sheets.put(id,yacht.scores.get(id));bonuses.put(id,upperBonus(yacht.scores.get(id)));}Map<String,Object>view=new LinkedHashMap<>();view.put("lobby",lobbyView());view.put("active",true);view.put("status",yacht.done?"FINISHED":"PLAYING");view.put("done",yacht.done);view.put("players",yacht.players);view.put("names",yacht.players.stream().map(id->repo.findById(id).map(Player::getNickname).orElse("퇴장")).toList());view.put("currentPlayer",yacht.players.get(yacht.turn));view.put("dice",yacht.dice);view.put("held",yacht.held);view.put("rolls",yacht.rolls);view.put("scores",sheets);view.put("upperBonuses",bonuses);view.put("pot",yacht.pot);view.put("message",yacht.message);return view;}
    private List<Map<String,Object>>lobbyView(){return yachtLobby.entrySet().stream().map(e->{Map<String,Object>item=new LinkedHashMap<>();item.put("playerId",e.getKey());item.put("nickname",repo.findById(e.getKey()).map(Player::getNickname).orElse("퇴장"));item.put("stake",e.getValue());item.put("ready",yachtReady.contains(e.getKey()));return item;}).toList();}
    record ChatMessage(long id,String nickname,String text,String sentAt){}
    static class YachtGame{List<String>players;Map<String,Map<String,Integer>>scores=new LinkedHashMap<>();int turn;int[]dice=new int[5];boolean[]held=new boolean[5];int rolls;long pot;boolean done;String message="첫 플레이어의 턴";YachtGame(List<String>p,long pot){players=p;this.pot=pot;p.forEach(id->scores.put(id,new LinkedHashMap<>()));}}
}
